### ISSUE TITLE
gridle_register_state changing gutters not working.

### ISSUE THREAD

**Issue by sikeane** [olivierbossel/gridle#100]
I am trying to change the gutter width / height depending on the registered state like so

```
// setup the grid (required) :
@include gridle_setup((

    context : $columns,
    gutter-width : ($gutter * .5),
    gutter-bottom : ($gutter * .5)

));

@include gridle_register_state ( bp-m , (

    min-width : $bp-m,
    gutter-width : $gutter,
    gutter-bottom : $gutter

) );

// there are several other states, but the gutters only change on this one

```

When then using the below the gutters to not change when the bp-m breakpoint is met. Do you have any ideas?

`@gridle (12 bp-m 6) `

I am using grunt-sass to complie.

**Comment by sikeane** [comment]
I have managed to get it working by calling 'gutter' after the state in the universal mixin. 

```
@gridle (
  12 
  bp-m 6 gutter
)
```

Is this normal behaviour or should the gutter be recalculated automatically?

**Comment by olivierbossel** [comment]
You can download the latest 2.0.45 release that will normally fix your issue.
Let me know!
Cheers!
