### ISSUE TITLE
CSS generated with gridle should be lint free

### ISSUE THREAD

**Issue by SimonHarte** [olivierbossel/gridle#107]
We currently get linting messages because of css that is generated by gridle.
The following warnings/errors seem to occur with my setup so far:

- `float can't be used with display: inline-block.`
- `Attribute selectors with *= are slow!`

> We use http://csslint.net/about.html

**Comment by olivierbossel** [comment]
Hi,

First of all, thanks for your feedback and your interest in gridle.
Linting is a large question. It's a good idea to try to have a lint free library, but sometimes, avoiding some linting rules is quite difficult and give to many features restrictions. Gridle goal is to work on all the major browsers and to allow that, I need to use some "hacks" or tricky selectors like the *= one for exemple.
I will take your feedback in consideration for the next releases and try to keep that in mind but I think that having a totally lint free framework is quite impossible.
You can try to process the bootstrap library in your favorite linting processor and you will see that there's even here a lot or warning and even some errors..

Let me know if you have any idea or some links to argument your request a little bit more and I will check.

Thanks again!

Cheers!
