### ISSUE TITLE
node-sass > 3.4.2 breaks this

### ISSUE THREAD

**Issue by dport512** [olivierbossel/gridle#108]
You get the error Error: Base-level rules cannot contain the parent-selector-referencing character '&'. 

Originally I thought you got the error with updated versions of gulp-sass (past 2.2), but apparently 2.2 still references a newer version of node-sass that throws the error below. 

Found the issue [here](https://www.bountysource.com/issues/9400189-base-level-rules-cannot-contain-the-parent-selector-referencing-character?utm_campaign=plugin&utm_content=tracker%2F283068&utm_medium=issues&utm_source=github)

Until this is fixed the workaround is to specify gulp-sass 2.2 and node-sass 3.4.2 in your package.json file

**Comment by LukeNZ** [comment]
Also getting this issue. Needs to be resolved.

**Comment by olivierbossel** [comment]
Hi guys,

Thanks for your feedbacks.
I have these versions and all is ok on my side...
Did you have any issues these days!

  "gulp-sass": "^2.3.2",
    "node-sass": "^3.8.0"

Cheers!

**Comment by Emnalyeriar** [comment]
@olivierbossel Could you list the sepcific verions you have installed and not defined in `package.json` file?
I've just tried installing different versions of both gulp-sass and node-sass and it just dosn't work. 
This is the error it produces:
```
Message:
    node_modules\gridle\sass\gridle\_mixins.scss
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.

       Backtrace:
        node_modules/gridle/sass/gridle/_mixins.scss:386, in mixin `-gridle-state`
        node_modules/gridle/sass/gridle/_api.scss:53, in mixin `gridle-state`
        styles/base/_typography.scss:324
        on line 386 of node_modules/gridle/sass/gridle/_mixins.scss
>>                              .state-#{$stateName} & {
   ----^

node_modules\gridle\sass\gridle\_mixins.scss
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.

       Backtrace:
        node_modules/gridle/sass/gridle/_mixins.scss:386, in mixin `-gridle-state`
        node_modules/gridle/sass/gridle/_api.scss:53, in mixin `gridle-state`
        styles/base/_typography.scss:324
        on line 386 of node_modules/gridle/sass/gridle/_mixins.scss
>>                              .state-#{$stateName} & {
   ----^
```

**Comment by Emnalyeriar** [comment]
Ok, I've just installed `node-sass@3.4.2` and it worked. Guess this is not fixed? Maybe you also don't have the newset version installed.
