### ISSUE TITLE
Nested grid classes are still too broad

### ISSUE THREAD

**Issue by mekwall** [olivierbossel/gridle#112]
We are having issues with the nested grid classes being way too broad. Even with the latest fix the issue for us persists.

For example, we have numerous classes containing `gr`, such as `progression` which will be targeted by the extremely broad `[class*="gr"]` selector. At least add the dash so that it becomes `[class*="gr-"]` or even better, try to get rid of the asterisk altogether.

**Comment by mauricecruz** [comment]
@mekwall I have a PR to address that. But it may cause issues with custom classes. I haven't used any custom classes yet though. 

https://github.com/olivierbossel/gridle/pull/109

**Comment by mekwall** [comment]
That's how I solved it as well. But it's merely a hack and as you said, it doesn't work with custom classes. That's not an issue for us though so I will continue to use the patched version until this is properly addressed.

**Comment by olivierbossel** [comment]
This has been fixed in the last release.
Thanks for your feedbacks.
Cheers!
