### ISSUE TITLE
Minimal support of browser/device

### ISSUE THREAD

**Issue by lauterry** [olivierbossel/gridle#113]
Hi

I want to know what is the minimal version of browsers supported by gridle.scss ?

Thank

Best regards

**Comment by olivierbossel** [comment]
Hi,

If you use the default driver, IE9 should be ok.
If you want to use the flex one, you will need IE10 at least and some flex properties are not even supported.

Is that ok for you?

Cheers!

**Comment by lauterry** [comment]
thx @olivierbossel

**Comment by newhope** [comment]
@olivierbossel You should put it in `README.md` dude.

And thanks for an awesome grid system.
