### ISSUE TITLE
gridle_register_column with mixins?

### ISSUE THREAD

**Issue by torrottum** [olivierbossel/gridle#29]
How can I register a custom column and use it with mixins?
I know I can do it with classes like this
```scss
@include gridle_register_column('1on5', 1, 5);
@include gridle_generate_classes();
```
```html
<div class="grid-1on5 item"></div>
```
I've tried

```scss
@include gridle_register_column('1on5', 1, 5);
.item {
   @include gridle('1on5');
}
```

**Comment by olivierbossel** [comment]
Hi man,

You can get the latest release with include your feature.
Let me know if all is ok for you like this.

Cheers!

**Comment by torrottum** [comment]
Awesome! I'll take a look soon
