### ISSUE TITLE
gridle_state mixin problem

### ISSUE THREAD

**Issue by pilaas** [olivierbossel/gridle#30]
I'm having following error when trying to compile using gulp-sass

```gridle/mixins:116: property "html#{_gridle_classname("#{$stateName}" must be followed by a ':'```

**Comment by olivierbossel** [comment]
By checking on gulp-sass documentation, it seems that the library used to compile sass is libsass. Libsass does not implement sass 3.3 features like maps that is used widely in gridle.. I think that for now you will have to change your compile script or to check for another grid system..
Hope that libsass will do a release soon...
If I'm wrong, I will be happy to be corrected by someone here :)

> The libsass library is not currently at feature parity with the 3.2 Ruby Gem that most Sass users will use, and has little-to-no support for 3.3 syntax


Cheers!

**Comment by pilaas** [comment]
Thanks a lot, I've switched already to manual compilation using ruby's sass package.
