### ISSUE TITLE
sass deprecation warning on passing name, a non-string value, to unquote()

### ISSUE THREAD

**Issue by kenaku** [olivierbossel/gridle#36]
Hi there! 
Nice grid system, thanks! 
Im getting this warnings:
DEPRECATION WARNING: Passing name xs, a non-string value, to unquote()
will be an error in future versions of Sass.
And the code is:

@include gridle_register_state( xs, (
    max-width : 480px,
    gutter-width : 10px
) );

**Comment by omgmog** [comment]
Yep this is a new `DEPRECATION WARNING`, as mentioned in this issue: https://github.com/sass/sass/issues/1607

Experiencing it on my projects that are using the latest `sass`. I think it's more annoying than anything for now, but will break in the future as it says.

**Comment by omgmog** [comment]
@kenaku It looks as if @olivierbossel has merged my fix now, so you can close this if you're happy!

**Comment by kenaku** [comment]
@omgmog, @olivierbossel 
Thanks, work like a charm!
