### ISSUE TITLE
Fixed width column?

### ISSUE THREAD

**Issue by dodozhang21** [olivierbossel/gridle#40]
Hi,

Is there way to create a fixed width column with this framework?

Column1 fixed at 300px
Column2 fill all of the rest of the space

Thanks

**Comment by olivierbossel** [comment]
Hi,

This is not part of the framework for now at least.. I will think about this for the next release..
Thanks for the interest you have about gridle.

Cheers miss!

**Comment by dodozhang21** [comment]
We are evaluating using yours for our bhg.com & parents.com redesign. 

So far I'm doing a workaround by redefining the columns via close percentage
e.g.

@include gridle(33, 100); // 33% and then set fix width: 300px on that column as well.

That seems to be working ok.

**Comment by olivierbossel** [comment]
Ok cool if it's ok like this.
For now I will not add something into the framework for fixed width columns cause it's not a very requested feature. But I keep that in mind for futur releases..

Cheers!
