### ISSUE TITLE
Register a custom column

### ISSUE THREAD

**Issue by dodozhang21** [olivierbossel/gridle#41]
I don't understand how this custom column function works. Once I registered it, how do I use it?

**Comment by olivierbossel** [comment]
Hi,

You can register a custom column like this :

```scss
@include gridle_register_column( '1on3' , 1, 3 );
```

This mean that your column will take 100 / 3 * 1 %

Then you can use this either in your scss or in your html like this :

```scss
.myCoolColumn {
     @include gridle('1on3');
}
```

```html
<div class="grid-10 grid-1on3-mobile">
   ... content here ...
</div>
```

This feature is useful when for exemple you have a grid setup that does not cover all your needs and that you need a special column width...
Grids configured with 12 columns are often enough cause you can divide 12 by 2, 3 and 4...
For exemple, if you have a grid that is configured like this :

```scss
@include gridle_setup((
   context : 20,
   name-multiplicator : 5,
   gutter-width : 20px
));
```

This mean that you will have 20 columns names "grid-5, grid-10, grid-15, grid-20, grid-30, grid-35, ..., grid-100", you may need a column to divide your content by 3, which will not exist by your default setup. In this case, you can register your custom column to cover your need...

Is that ok for your like answer?

Let me know if you need more informations...

Cheers!

**Comment by dodozhang21** [comment]
This is clear.

Thank you!

**Comment by dodozhang21** [comment]
I'd suggest you add this information to your documentation as it wasn't very straightforward to me.
