### ISSUE TITLE
An option for add custom css on the big selector class rule for all grid elements

### ISSUE THREAD

**Issue by pieplu** [olivierbossel/gridle#43]
Hi!

Can you let us the oportunity to add custum css on the big rule of all grid element ?

In my case, my big selector class rules looks-like this:

     .grid-0, .grid-1, .grid-2, .grid-3, .grid-4, .grid-5, .grid-6, .grid-7, .grid-8, .grid-9, .grid-10, .grid-11, .grid-12, .grid-xxs-0, .grid-xxs-1, .grid-xxs-2, .grid-xxs-3, .grid-xxs-4, .grid-xxs-5, .grid-xxs-6, .grid-xxs-7, .grid-xxs-8, .grid-xxs-9, .grid-xxs-10, .grid-xxs-11, .grid-xxs-12, .grid-xs-0, .grid-xs-1, .grid-xs-2, .grid-xs-3, .grid-xs-4, .grid-xs-5, .grid-xs-6, .grid-xs-7, .grid-xs-8, .grid-xs-9, .grid-xs-10, .grid-xs-11, .grid-xs-12, .grid-sm-0, .grid-sm-1, .grid-sm-2, .grid-sm-3, .grid-sm-4, .grid-sm-5, .grid-sm-6, .grid-sm-7, .grid-sm-8, .grid-sm-9, .grid-sm-10, .grid-sm-11, .grid-sm-12, .grid-md-0, .grid-md-1, .grid-md-2, .grid-md-3, .grid-md-4, .grid-md-5, .grid-md-6, .grid-md-7, .grid-md-8, .grid-md-9, .grid-md-10, .grid-md-11, .grid-md-12, .grid-lg-0, .grid-lg-1, .grid-lg-2, .grid-lg-3, .grid-lg-4, .grid-lg-5, .grid-lg-6, .grid-lg-7, .grid-lg-8, .grid-lg-9, .grid-lg-10, .grid-lg-11, .grid-lg-12

and I need to define a max-width 100%.

I don't think than copy past all in custom styles is a good worflow.

Thanks in advance.

**Comment by olivierbossel** [comment]
Hi,

First, thanks for using Gridle.
For your specific need, is this css can work for you?

```scss
[class*="grid-"] {
   max-width: 100%;
}
```

Gridle is at this root, designed to have only the columns classes to begin with grid-..., this allows you to make the selector described above.

Let me know if it's ok for you like this?

Cheers!

**Comment by pieplu** [comment]
Hi, 

Thanks to response me.

I think I was not very understandable ^^.
My matter is not to find a good selector, juste a "Nice to have",
to let use customise more Gridle.

In my case, I want be able to generate class like this:

    .grid-0, [...] .grid-lg-12 {
        float: left;
        direction: ltr;
        padding-left: 10px;
        padding-right: 10px;
        custom code injected in this place
    }

Maybe put an array in parameter of the mixin

**P.S:** I don't really like the attribut selector ([class*="grid-"]),
too many side-effect, like ".hagrid-and-harry-potter", or "box__grid--blue". When I can, I prefer not to use it.

**Comment by olivierbossel** [comment]
Ok I see..
I will think about that for the next release..
Cheers!

**Comment by conorluddy** [comment]
That's not really an issue though? 

You could use something like this:
[class^="grid-"],
[class*=" grid-"]{
    ...
}
(Note the new space and ^)

Or you could just define your own general class like '.grid-all{max-width:100%}' and apply it where you need it...

**Comment by olivierbossel** [comment]
I man,
Just to let you know that your feature request will be part of the next release that will be out in the next few weeks. I'm currently working on it.
Cheers!

**Comment by pieplu** [comment]
Hi @olivierbossel , thanks for the update :)

@conorluddy, thanks, but the matter is not to find the best selector, they will always perfectible (.grid-colored match too, for example), it's to customise more gridle :)

**Comment by olivierbossel** [comment]
Hi guys,

This will be part of the next major release that will be out very soon. Stay tuned!
