### ISSUE TITLE
Including ad hoc states

### ISSUE THREAD

**Issue by veganista** [olivierbossel/gridle#45]
The documentation has an example like this in the [Mixins Section](http://gridle.org/documentation/1.3.3#documentation_05.mixins.md):

    @include gridle_state ( {min-width} , {max-width} ) { 
        ...
    }

However when i try to do:

    @include gridle_state( 200px, 500px ){
        ...
    }

I get the following error:

`Error: $map2: 200px is not a map for 'map-merge'`

I feel like the documentation is slightly misleading here

**Comment by olivierbossel** [comment]
Hi man,

That's a good point. This has been lost in the dark night of my brain.. :)
I will make sure this is working asap and add this in the test.scss file that I've added recently to be sure that I don't miss any compatibility in futur releases.

Thanks again for your interest in gridle

Cheers!

**Comment by veganista** [comment]
No problem.

There's not a project i have doesn't use gridle anymore its (almost) perfect!

Regarding testing i ran across this the other day: http://mts.io/2014/04/02/sass-unit-testing/

Not sure how mature the projects mentioned are but probably a good idea for setting up tests.

**Comment by olivierbossel** [comment]
Thanks for the kind message, this is why I continue to improve it day by day :)
I will take a look at your link, thanks.

Cheers!
