### ISSUE TITLE
Percentage widths

### ISSUE THREAD

**Issue by jantm** [olivierbossel/gridle#47]
In a 12-column grid `grid-4` elements are 33.33333% wide and `grid-8` elements are 66.66667% wide.
The problem is that if you put two `grid-4` elements and a `grid-8` under them, the `grid-8` element will be slightly wider.

Try this in Chrome:

    <div style="width: 1200px; margin: 0 auto">
        <div class="grid-4" style="height:50px; background:red"></div>
        <div class="grid-4" style="height:50px; background:red"></div>
        <div class="grid-8" style="height:50px; background:green"></div>
    </div>

Apparently the `margin: 0 auto` in the wrapper `div` does affect the widths.

I noticed that Bootstrap uses more decimal places in the percentage values; for this case they would be: 33.33333333% and 66.66666667%. 
And... it works!

**Comment by olivierbossel** [comment]
Hi,

This is more an sass configuration option. You can add in your config.rb file this

```ruby
Sass::Script::Number.precision = 8
```

This will increase the decimal precision and make what you want..

Let me know if it's ok like this!

Cheers!

**Comment by jantm** [comment]
Yes, indeed, that probably resolves the issue (in my case I resolved it with a proper option in my gruntfile). 

I just thought that maybe there was a way to ensure the creation of "proper percentages" that wouldn't depend on individual settings. Anyway, that's for you to consider - I'm ok with changing the config.
