### ISSUE TITLE
Flexbox as an option

### ISSUE THREAD

**Issue by spaceribs** [olivierbossel/gridle#49]
Friendly feature request here, and it may not be totally possible, but it would be great to allow flexbox as a choice instead of floating. I've started to see more and more grid systems use Flexbox (http://ionicframework.com/) and while i'm sure it's a lot of effort it's worth some consideration.

**Comment by mahnunchik** [comment]
+1

**Comment by spaceribs** [comment]
@olivierbossel Adding this for some food for thought: https://philipwalton.github.io/solved-by-flexbox/demos/grids/

**Comment by rafegoldberg** [comment]
**`+1`** for a `flexbox` option!

**Comment by craigmdennis** [comment]
+1

**Comment by olivierbossel** [comment]
Hi guys,

The next major release will have full flex support (as a choice) so stay tuned, it comes very soon!

Cheers

**Comment by spaceribs** [comment]
@olivierbossel NICE thanks for the update!
