### ISSUE TITLE
LICENSE.md needed

### ISSUE THREAD

**Issue by spaceribs** [olivierbossel/gridle#50]
possibly MIT?

https://github.com/spaceribs/blobeval/blob/master/LICENSE.md

**Comment by olivierbossel** [comment]
yes of course. I will add this in the next release.
Cheers!

**Comment by stevenaanen** [comment]
Hi. I'm planning to use Gridle for a client's project. It's necessary for them that the licensing is absolutely clear to avoid any problems. It would be great if a LICENSE file could be added to the repo indeed, otherwise I can't use it.

**Comment by olivierbossel** [comment]
Hey man, will do that tomorrow :)

**Comment by olivierbossel** [comment]
Done !

**Comment by stevenaanen** [comment]
Awesome, thanks man!

**Comment by olivierbossel** [comment]
you're welcome
