### ISSUE TITLE
Output css contains only comments

### ISSUE THREAD

**Issue by cdarken** [olivierbossel/gridle#51]
Hi. I found your framework and I was trying to take it for a spin. After issues with gulp-sass, I moved to gulp-ruby-sass.
It compiles without problems, but I don't see any css in the output. This is my code:
```
@import "gridle/gridle";

@include gridle_setup( (
  context : 12,
  gutter-width : 0
  // etc...
) );

@include gridle_register_state( mobile , (
    max-width : 400px
) );
@include gridle_register_state( tablet, (
    min-width : 401px,
    max-width : 767px,
    gutter-width : 30px     // change the gutters for this state
) );
```
I'm invoking it from cli, with:
`sass sass/alpege.scss css/alpege.css -I vendor/gridle/sass`

Any hints what I'm doing wrong?

**Comment by olivierbossel** [comment]
Hi,

You forget the @include gridle_generate_classes at the end.

Cheers!

**Comment by cdarken** [comment]
Thanks a lot, I was skimming over the documentation, it somehow escaped me.
