### ISSUE TITLE
error with libsass 3.1.0 on _common-mixins.scss:32

### ISSUE THREAD

**Issue by lucmilland** [olivierbossel/gridle#52]
hello,
I try to use gridle in a Django project with django-libsass with uses libsass through libsass-python .
When compiling my scss file, I get this error :
> gridle/_common-mixins.scss:32: error reading values after

did I miss something or is this a real bug ?

to reproduce the error :
- boot a fresh ubuntu Precise 
- clone libsass git repo and checkout 1.3.0 tag branch
- clone sassc git repo and checkout 1.3.0 tag branch
- compile
- checkout gridle git repo
- sassc gridle/sass/tests.scss
- doh !

regards,
Luc

ps : ok, it seems to be a libsass bug : https://github.com/sass/libsass/issues/548

**Comment by mahnunchik** [comment]
+1

**Comment by juicyfish** [comment]
+1
Commented in the older raised Issue.

**Comment by veganista** [comment]
This **may** have been fixed with the release of [libsass 3.2.0](https://github.com/sass/libsass/releases/tag/3.2.0).

**Comment by mahnunchik** [comment]
This error has been fixed!

Only the following lines cause error:
```scss
@if $ie7-support == true {
  *width: expression((this.parentNode.clientWidth/#{$context}*#{($columns / $name-multiplicator)} - parseInt(this.currentStyle['paddingLeft']) - parseInt(this.currentStyle['paddingRight'])) + 'px');
}
```
https://github.com/olivierbossel/gridle/blob/master/sass/gridle/_mixins.scss#L244

```
Error: bower_components/gridle/sass/gridle/_mixins.scss
  244:11  unterminated interpolant inside IE function expression((this.parentNode.clientWidth/#{$context}*#{($columns / $name-multiplicator)
```

* gulp-sass@2.0.0
* node-sass@3.0.0
* "libsass": "3.2.2",

**Comment by mahnunchik** [comment]
I think this issue can be closed.

I've created new one for the last error: https://github.com/olivierbossel/gridle/issues/57
