### ISSUE TITLE
Mixin grid gutter behavior

### ISSUE THREAD

**Issue by Luwdo** [olivierbossel/gridle#53]
I am building a site that had grids of artwork, I would like to still use griddle to format these grids. The gutter on these grids should be different from the rest of the site.

Is it possible to set the gutters for states with a mixin?

I have tried a few things after skimming the codebase.

This is from my failed attempts, I imagine it should look something like this but I can't find the setting.

```
.gallery-artwork{
    @include gridle(4); //set to 10% in the main settings
    @include gridle(6,"tablet");
    @include gridle(12,"mobile");
    //@include gridle_gutter(50px);
    //@include gridle_gutter(30px,"tablet");
    //@include gridle_set_state_var( gutter-width , 50px);
    //@include gridle_set_state_var( gutter-width , 30px, tablet );
    @include gridle_set((
	gutter-width : 50px,
    ));
}
```

Could you steer me in the right direction?

**Comment by mahnunchik** [comment]
ping @olivierbossel

@Luwdo  I use the following settings:
```scss
@include gridle_setup ((
  context: 12,
  gutter-width: 40px
));

@include gridle_register_state(xs, (
  max-width : 768px
));
@include gridle_register_state(sm, (
  min-width : 768px,
  gutter-width: 20px
));
@include gridle_register_state(md, (
  min-width : 992px
));
@include gridle_register_state(lg, (
  min-width : 1280px,
  gutter-width: 60px
));
```

**Comment by olivierbossel** [comment]
Hi guys,
In the current version, it's not possible but I will add this in the next release cause it's a good idea.
Mahnunchik is right, you can specify different gutters by states, but not for a particular element for now.
Make sure to stay in touch with the next release that will be out in the next few weeks

Cheers!

**Comment by olivierbossel** [comment]
Hi guys,

The next major release will be out soon. Stay tuned!

Cheers
