### ISSUE TITLE
Allow to specify context with gridle_set

### ISSUE THREAD

**Issue by mahnunchik** [olivierbossel/gridle#58]
Allow to specify `context` with `gridle_set`.

Works:
```scss
@include gridle(1, 3);
```

Not works:
```scss

@include gridle_set((
  grid: 1,
  context: 3
));
```

**Comment by rafegoldberg** [comment]
**`+1`** on this suggestion. This'd be a great way to customize your grid layouts on the fly which is one of my biggest (and only) gripes with Gridle...

**Comment by olivierbossel** [comment]
Hi guys,

This is a good request, I will integrate this in a 1.x update and this will be covered also in the next major release that arrive very soon. Stay tuned!

Cheers!

**Comment by olivierbossel** [comment]
Hi,

In release 2.0.0 you can do :

```scss
@include gridle_set((
   grid : 1 3
));
```

Hope that's good for you!
Cheers

**Comment by kalanda** [comment]
@olivierbossel that way to specify context is not well documented. 

Documentation of current revision (2.0.44) [here](http://gridle.org/documentation/2.0.44#mixins-what-is-the-context-) shows this way that throws an error:

`@include gridle(1, 3);`

But through this issue I'd find the working way but I doesn't find any reference to that in the current docs.
```
@include gridle_set((
   grid : 1 3
));
```

Awesome framework by the way :+1:
