### ISSUE TITLE
The state gutter-width doesnt calculated for .gutter-{state}-* classes

### ISSUE THREAD

**Issue by kvaezo** [olivierbossel/gridle#60]
I found a bug with this - in the _generate_mixins.scss on line 108, 112, 116, 120 and 124 (in _gridle_generate_helper_classes mixin)

The bug is that the gridle_margin() function didn't get the state, so it is going to calculate whith the default gutter-width. If you add it as the second argument, it calculates right.

ps.: sorry about my bad english

**Comment by rafegoldberg** [comment]
I've experienced problems with the `margin()` function as well. It seems like a great utility so it'd be nice to get this working as expected!

**Comment by olivierbossel** [comment]
this has been updated in 2.x release
