### ISSUE TITLE
Custom Class Names

### ISSUE THREAD

**Issue by rafegoldberg** [olivierbossel/gridle#64]
Quick question: so by default Gridle uses `.grid-1` or `.grid-mobile-6`, for example. But I might like to use `.block-1` or `.block-mobile-6`. So what I'm wondering is if Gridle provides a way to customize the class naming conventions? Thanks for any tips/info!

**Comment by veganista** [comment]
Check out the Class Patterns documentation [here](http://gridle.org/documentation/1.3.3#documentation_09.advanced-settings.md)

You probably want to do this:

    $gridle-grid-name-pattern: ('block','%-','%state','%-','%count');

**Comment by rafegoldberg** [comment]
Oh woah, I've used Gridle's stately naming patterns with the `generate_custom_class` function before but I never knew about the `$grid-name-pattern` global setting – v. cool. Thanks for the tip!
