### ISSUE TITLE
generate-prefix-classes causing unknown error with gulp-sass

### ISSUE THREAD

**Issue by craigmdennis** [olivierbossel/gridle#65]
Error details (not helpful):

```
Message:
    src/sass/app.scss
  undefined:undefined  unknown
Details:
    status: 5
    messageFormatted: src/sass/app.scss
  undefined:undefined  unknown
```

The gridle setup looks like this:

```scss
// Setting up the grid
@include gridle_setup( (
  context: 12,
  gutter-width: 1.5em,
  direction: ltr,
  generate-prefix-classes: false,
  generate-suffix-classes: false
));
```

When I turn `generate-prefix-classes` and `generate-prefix-classes` to `true` the error goes away.

I'll try and put a test case together when I have some time.

**Comment by Loque-** [comment]
I am getting this issue also and can confirm it is happening when setting 'classes' property to false also.  Apologies for not being able to post more information at this time!
