### ISSUE TITLE
Setting gridle to debug compilation errors in _mixins.scss

### ISSUE THREAD

**Issue by Sensiblemnd** [olivierbossel/gridle#67]
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.
        on line 149 of /gridle/gridle/_mixins.scss, in `gridle_state'

Error: Base-level rules cannot contain the parent-selector-referencing character '&'.
        on line 116 of /gridle/gridle/_mixins.scss, in `gridle_state'

**Comment by veganista** [comment]
What version of SASS and gridle are you using?

**Comment by Sensiblemnd** [comment]
I had an old version of sass. That was the cause of the error
