### ISSUE TITLE
Error with multiple contexts passed to gridle_state

### ISSUE THREAD

**Issue by gkinsman** [olivierbossel/gridle#69]
> events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: bower_components\gridle\sass\gridle\_functions.scss
  338:12  argument `$map2` of `map-merge($map1, $map2)` must be a map

> Backtrace:
	bower_components/gridle/sass/gridle/_functions.scss:338, in function `map-merge`
	bower_components/gridle/sass/gridle/_functions.scss:338, in function `_gridle_get_media_query`
	bower_components/gridle/sass/gridle/_mixins.scss:156, in mixin `gridle-state`
	stdin:55, in mixin `sidebar`
	stdin:467
    at options.error (c:\Projects\Work\ProjectName\ui\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:276:32)

when doing 
```
@mixin sidebar {
  @include gridle_state(mobile tablet) { @include gridle_suffix(0); }
}
```

those states are registered like this:

```
@include gridle_register_state ( tablet , (
        min-width : 481px,
        max-width: 768px,
        gutter-width : 10px
) );

@include gridle_register_state ( mobile , (
        max-width : 480px,
        gutter-width : 10px
) );
```

**Comment by olivierbossel** [comment]
Hi,

Due to limitation of sass, you need to write your code like so:

```scss
#mixin_sidebar {
    @include gridle_suffix(0, mobile tablet);
}
```

The code you have written will be valid with the release 2.0.0 that will come very soon.
Stay tuned!

Cheers
