### ISSUE TITLE
Grid debug overlay

### ISSUE THREAD

**Issue by niwlondon** [olivierbossel/gridle#70]
Is it currently possible to view the grid used (as a background image). Susy does this, and its a very useful feature while building.

Like this: http://codepen.io/zellwk/pen/jDFdI

Many thanks

**Comment by olivierbossel** [comment]
Hi,

This will be part of the 2.0.0 release that will come very soon.
The 2.0.0 release will have a lot more features, flex compatibility, etc...
Stay tuned :)

Cheers!
