### ISSUE TITLE
Does the flex driver support IE10?

### ISSUE THREAD

**Issue by Emnalyeriar** [olivierbossel/gridle#78]
As far as I know IE10 supports flex but with a bit different syntax. Does gridle based on flex work fine on IE10?

**Comment by olivierbossel** [comment]
Hi man,

Thanks for your interest in gridle.
IE10 is supported by the flex driver for the most part. The only thing that is not supported is the nowrap class. That's cause IE10 does not support the flex-wrap property at all so I can't do anything for that sorry...
Check out the demo page http://olivierbossel.github.io/gridle/demo-flex.html to see if that seems viable for you :)

Cheers!

**Comment by Emnalyeriar** [comment]
Thanks for the detailed answer! I think it would be good to put this info somewhere on the page.
