### ISSUE TITLE
Crash with node-sass 3.4.0

### ISSUE THREAD

**Issue by exophunk** [olivierbossel/gridle#79]
Hi Olivier,

It seems that gridle crashes with the current version of node-sass or libsass.

gridle: 2.0.4
gulp-sass: 2.0.4
node-sass: 3.3.3
libsass: 3.2.5

--> works perfect.

gridle: 2.0.4
gulp-sass: 2.0.4
node-sass: **3.4.0**
libsass: **3.3.0**

(node-sass and libsass are dependencies of gulp-sass) 

This one crashes:
```
[14:19:37] gulp-notify: [Error running Gulp] resources/scss/vendor/gridle/_mixins.scss
  295:5  Extend directives may only be used within rules.
```

I managed to make it work by manually downgrade to node-sass 3.3.3 -> `npm install node-sass@3.3.3 --save-dev`, so I'm pretty sure it is an issue with `node-sass > 3.3.3` or `libsass > 3.2.5`...

Thanks, Robert

**Comment by olivierbossel** [comment]
#80
