### ISSUE TITLE
Error:  Extend directives may only be used within rules

### ISSUE THREAD

**Issue by GR3S** [olivierbossel/gridle#80]
Building scss with imported gridle using gulp-sass (that uses node-sass, latest versions) I'm getting this error:
```
[12:03:08] Starting 'css:build'...
Error in plugin 'sass'
Message:
    bower_components/gridle/sass/gridle/_mixins.scss
  295:5  Extend directives may only be used within rules.
[12:03:08] Finished 'css:build' after 393 ms
```

**Comment by rawzone** [comment]
Same problem here

**Comment by olivierbossel** [comment]
Hi guys,

This has been fixed in 2.0.41. Let me know if it's ok on your setup (it's always hard to be 100% sure that will works for everyone with all these different environments...)

Cheers!

**Comment by rawzone** [comment]
Thanks a ton @olivierbossel !

Works like a charm. Both on my development workstation running Arch Linux and on stating server running FreeBSD 10.2-RELEASE.

**Comment by GR3S** [comment]
Thanks! Now it's ok.
