### ISSUE TITLE
Ability to change "gr" and "@" in Version 2.x? 

### ISSUE THREAD

**Issue by Landish** [olivierbossel/gridle#81]
Hi, @olivierbossel 

First of all, thanks for having such a great grid system, I totally love it.

I have a question though,  I wasn't able to change the `.gr` prefix and `@` symbol on state classes. 
I'm not a big fan of using `@` symbols in css class names an I prefer to change it, for example with `-` dashes.

Same thing with `.gr` prefix, all of my projects were built with 1.X version and I want to update it up to 2.X version, but because of this, I'm a lil bit afraid of doing that. 

So, is there any possible way to change these 2 things? Or you "force" to use this names and symbols?

I tried using solutions found #64 and #74, but with no luck.

**Comment by olivierbossel** [comment]
Hi man,

First of all, thanks a lot for your interest in gridle, I appreciate that a lot!

For your question, you can change all the class names by using this advanced feature :

http://gridle.org/documentation#advanced-settings-classes-names

For the @, you will have to override all the classes names maps and there's many but at least you have this choice.
For the gr- you can override only the classes that have this in.

The 2.x release is a major one so I don't have take care so much of the compatibility with previous version unfortunately. This was a little to hard to do if I wanted to push gridle further.

Let me know if this answer your question :)

Cheers!

**Comment by Landish** [comment]
Oh, I get it:

I did the following:
```sass
@include gridle_set_classname_map(grid, ('my_grid','-','%column','-','%state'));
@include gridle_set_classname_map(grid-adapt, ('my_grid','-','adapt','-','%state'));
@include gridle_set_classname_map(grid-table, ('my_grid','-','table','-','%state'));
...
```

and got the result, that I was expecting. 

But, I noticed something.

In the [gridle/_settings.scss](https://github.com/olivierbossel/gridle/blob/master/sass/gridle/_settings.scss#L9) file there is a variable/list:

```sass
$_gridle-names-separators : ('-','--','_','__','@');
```
which, I believe is not used anywhere.

And I'm thinking that this last item (@ symbol) should be used as state separator, but on `$_gridle-packages ` it's "hardcoded". 

So, maybe we can do the following:
```sass
$_gridle-names-separators : ('-','--','_','__','@') !default;
```

```sass
$_gridle-packages : (
	container 							: (
		classname 							: ('container',unquote(nth($_gridle-names-separators, 5)),'%state'),
		package 							: default container
	),
	row 								: (
		classname 							: ('row','-','%reverse',unquote(nth($_gridle-names-separators, 5)),'%state'),
		package 							: default row
	),
	row-align 							: (
		classname 							: ('row','-','align','-','%align',unquote(nth($_gridle-names-separators, 5)),'%state'),
		package 							: default row-align
	),
...
```

In that case, if someone will create the:
```sass
$_gridle-names-separators : ('-','--','_','__','@_this_symbol_should_be_replaced_by_developer'); 
```
It will solve the "@ symbol issue".

And about the `.gr`, maybe we can move it to `settings` objects?

```sass
// default settings
$settings : (
    classes-grid : '.gr'    // the prefix name used for all columns 
);
@include gridle_setup($settings);
```

Or something like that.

In these case, developers can easily change the class names and it's structure by setting these options. rather than using `gridle_set_classname_map` mixin for everything.

**Comment by joomlolo** [comment]
hello everybody,
Thanks for your work @olivierbossel!
I am agree to be able to change the "gr", I need too.and it is a good idea if you have more than one grid,better than use prefix.
Regards.

**Comment by Landish** [comment]
Well, I just did.

If someone prefers, the 1.X version style css classes for grids, there you go.

Place the following lines of code before:

```sass
@include gridle_generate_classes();
```

```sass
@include gridle_set_classname_map(container, ('container','-','%state'));
@include gridle_set_classname_map(row, ('row','-','%reverse','-','%state'));
@include gridle_set_classname_map(row-align, ('row','-','align','-','%align','-','%state'));
@include gridle_set_classname_map(row-full, ('row','-','full','-','%state'));
@include gridle_set_classname_map(row-debug, ('row','-','debug','-','%state'));
@include gridle_set_classname_map(nowrap, ('nowrap','-','%state'));
@include gridle_set_classname_map(wrap, ('wrap','-','%state'));
@include gridle_set_classname_map(col, ('col','-','%reverse','-','%state'));

@include gridle_set_classname_map(grid, ('grid','-','%column','-','%state'));
@include gridle_set_classname_map(grid-table, ('grid','-','table','-','%state'));
@include gridle_set_classname_map(grid-adapt, ('grid','-','adapt','-','%state'));
@include gridle_set_classname_map(grid-grow, ('grid','-','grow','-','%state'));
@include gridle_set_classname_map(grid-centered, ('grid','-','centered','-','%state'));

@include gridle_set_classname_map(push, ('push','-','%column','-','%state'));
@include gridle_set_classname_map(pull, ('pull','-','%column','-','%state'));
@include gridle_set_classname_map(prefix, ('prefix','-','%column','-','%state'));
@include gridle_set_classname_map(suffix, ('suffix','-','%column','-','%state'));

@include gridle_set_classname_map(hide, ('hide','-','%state'));
@include gridle_set_classname_map(show, ('show','-','%state'));
@include gridle_set_classname_map(show-inline, ('show','-','inline','-','%state'));
@include gridle_set_classname_map(not-visible, ('not','-','visible','-','%state'));
@include gridle_set_classname_map(visible, ('visible','-','%state'));
@include gridle_set_classname_map(float, ('float','-','%float','-','%state'));
@include gridle_set_classname_map(clear, ('clear','-','%float','-','%state'));
@include gridle_set_classname_map(clear-each, ('clear','-','each','-','%count','-','%state'));

@include gridle_set_classname_map(gutter, ('gutter','-','%side','-','%state'));
@include gridle_set_classname_map(no-gutter, ('no','-','gutter','-','%side','-','%state'));
@include gridle_set_classname_map(auto-height, ('auto','-','height','-','%state'));
@include gridle_set_classname_map(order, ('order','-','%column-count','-','%state'));
```
