### ISSUE TITLE
gridle_container() / gridle(container) -- what's the purpose?

### ISSUE THREAD

**Issue by ManneW** [olivierbossel/gridle#82]
Hi!

I ran into some trouble when upgrading from Gridle 1.x to 2.0.4. The main issues were related to clearfix.

Then I came across issue #15.

I recognize the same behavior: ``gridle_container()`` and ``gridle(container)`` doesn't do anything at all – no rules added inside the class, whatsoever.

Then I simply wonder; what's the purpose of these to mixins if they're not supposed to do anything? 
Sorry if I've misinterpreted the answer to #15 :-) Anyway it would be great if someone could shed some light on this.

BR.

**Comment by olivierbossel** [comment]
Hi man,

Thanks for your feedback and your interest in gridle. Appreciate that a lot!

There was an issue with the container. It's not required but it has a clearfix on it that were not working in last release. Sorry for that.
Normally you can get the 2.0.41 release and all will work as expected.
Let me know!

Cheers!
