### ISSUE TITLE
Homepage on firefox

### ISSUE THREAD

**Issue by Emnalyeriar** [olivierbossel/gridle#83]
First of all - I really like your grid and I was using it a bit pre 2.0. Still waiting to use the new version in a major project. 
When it comes to the grid homepage there are elements that look different on FF and Chrome. I am not sure if its a problem with the grid or just with the homepage styling but the main buttons "demo" and "download" are stacked on top of each other and the yellow nav is not in one line on Firefox comapred to Chrome.
![gridle](https://cloud.githubusercontent.com/assets/7673503/10905425/667dacf0-821a-11e5-92bf-88c251b95c06.jpg)

**Comment by olivierbossel** [comment]
hi man,

Thanks for your feedback. Appreciate that a lot!
There's actually a weird thing on firefox when row-align is used. This has been fixed in 2.0.42
Thanks again

Cheers!
