### ISSUE TITLE
Improve clear-each-*

### ISSUE THREAD

**Issue by exophunk** [olivierbossel/gridle#85]
Hi, I'd like to propose a small improvement to the clear-each-* class.

Instead of using `:nth-child(2n+1)`, I would use (example of clear-each-2):

```
.clear-each-2 > [class*='gr-']:nth-of-type(2n+1) {
  clear: left;
}
```

This way, only `gr-` classes are touched. This has a few advantages:

- The `.row` container doesn't have to be the direct parent, but can be used further up (e.g. outside a scrolling-container or something fancy)
- If other DOM-Elements are in between the `gr-*` items, they don't interfere with the float clearing. For example, I am using a infinite-scroll plugin which adds an invisible `div.pagination` element sometimes inbetween. This broke my clearing rules - even if it's invisible - as it was counted as another :nth-child().

With `:nth-of-type()`, we can make sure only gridle-related classes are touched.

Thanks,

Robert

**Comment by olivierbossel** [comment]
Hi,

Thanks for your feedback. I have integrated your improvement request.

Hope it's ok like this :)

Cheers!
