### ISSUE TITLE
The row-full class enables the horizontal scrollbar

### ISSUE THREAD

**Issue by GianlucaGuarini** [olivierbossel/gridle#86]
In the griddle demo is visible the horizontal scrollbar.The issue seems to be the example using the `row-full` class

![screen shot](https://cloud.githubusercontent.com/assets/879612/11028650/a42f58c8-86c0-11e5-8f24-9fc32b5fbda4.png)

**Comment by GianlucaGuarini** [comment]
I think `vw` could be problematic http://community.sitepoint.com/t/100vw-and-scrollbars/196480

**Comment by jannikegger** [comment]
same issue here - but only for Internet Explorer 10+11 :(
what seems to be a bit strange for me - in an earlier version i thought it worked correctly.

**Comment by olivierbossel** [comment]
Hi guys,

Thanks for your feedbacks.
You're right, the vw works a little bit strange on some browsers. The only workaround I know at this time is to put an overflow-x: hidden; on the body or somewhere..

If you have any better idea to solve that issue let me know :)

Cheers and thanks for your interest!
