### ISSUE TITLE
Custom column 1on5, 2on5, 3on5, 4on5 and 5on5

### ISSUE THREAD

**Issue by beeInteractive** [olivierbossel/gridle#87]
Hi!

I use gridle on every project and I love it!

But since a few days, I try to achieve some grid construction without success.. And the documentation about this doesn't help me.. I'm trying to construct a five columns grid. I found the "1on5" class name, which is working, but when I register the other class names like this: 

// register special columns
@include gridle_register_column("1on5", 1, 5);
@include gridle_register_column("2on5", 2, 5);
@include gridle_register_column("3on5", 3, 5);
@include gridle_register_column("4on5", 4, 5);
@include gridle_register_column("5on5", 5, 5);

It doesn't work.. Can you help me going in the right direction? Did I miss a step?

Thank you in advance,
Cheers!

**Comment by olivierbossel** [comment]
Hi,

Thanks for your feedback!
Did you call gridle_generate_classes mixin ?
Can you post the code you use to setup and generate the classes ?
Which version are you using?

Cheers!

**Comment by beeInteractive** [comment]
Hi!

This is my configuration at this time. It seems to be working but I was wondering if there's maybe a better way to achieve this.

Cheers!

```
@include gridle_register_column( '1on5' , 1, 5 );
@include gridle_register_column( '2on5' , 2, 5 );
@include gridle_register_column( '3on5' , 3, 5 );
@include gridle_register_column( '4on5' , 4, 5 );
@include gridle_register_column( '5on5' , 5, 5 );

.gr-1on5 { @include gridle_grid("1on5"); }
.gr-2on5 { @include gridle_grid("2on5"); }
.gr-3on5 { @include gridle_grid("3on5"); }
.gr-4on5 { @include gridle_grid("4on5"); }
.gr-5on5 { @include gridle_grid("5on5"); }
```

**Comment by olivierbossel** [comment]
If you like you can do something like this :

```scss
.gr-1on5 { @include gridle_grid(1/5);
// etc...
```

When the passed parameter is less than 1, the width will be calculated as ratio of 100%

Let me know

**Comment by beeInteractive** [comment]
Yep it worked whithout the all "gridle_register_column" block. Thank you!
