### ISSUE TITLE
Gridle 2.0.43 unbuildable under libsass 3.3

### ISSUE THREAD

**Issue by LukeNZ** [olivierbossel/gridle#92]
[Error: resources\assets\css\gridle\gridle\_functions.scss
  834:8  argument `$list` of `nth($list, $n)` must not be empty]
  message: 'resources\\assets\\css\\gridle\\gridle\\_functions.scss\n  834:8  argument `$list` of `nth($list, $n)` must not be empty',
  column: 8,
  line: 834]

No idea how to resolve this. Worth noting that while this is most likely libsass' problem (when is it not, lol), it does appear to be caused by a regression from Gridle 2.0.2 (which works fine).

**Comment by olivierbossel** [comment]
Hi,

Thanks for your feedback.
Unfortunately, I can't reproduce your issue...
Can you send me more details ?

Thanks
