### ISSUE TITLE
Use !important for the show/hide classes

### ISSUE THREAD

**Issue by GianlucaGuarini** [olivierbossel/gridle#98]
The use of the classes `hide` or `show` gets overridden by the default `display` property applied to any DOM element. The issue is simply reproducible and it's is really annoying:
```css
.el {
  display: inline-block;
}
```

```html
<div class="el hide@mobile">
  I should not be visible on mobile!
</div>
```
The element will be always visible because the `.el` class will override the gridle helper classes
I can make a pull request if you want

**Comment by olivierbossel** [comment]
Hi,

I think this is more like an css order issue, isn't it?
Your .el element is declared after your grid elements no?
If you have any good solution I will be pleased to discuss about it with you as well.

Cheers!
