### ISSUE TITLE
.row responsive margin issue

### ISSUE THREAD

**Issue by JoshRiser** [olivierbossel/gridle#99]
I have a few responsive states registered like so

```
@include gridle_setup((
	context: 12,
	gutter-width: 60px
));
@include gridle_register_state(xl, (max-width: 1200px, gutter-width: 50px));
@include gridle_register_state(lg, (max-width: 980px, gutter-width: 40px));
```
Naturally, when I'm on a screen larger than 1200px wide, my **.row** class would put this on the element.
```
margin-left: -30px;
margin-right: -30px;
```

However, when I get down to the first breakpoint, where the gutter changes (1200px), the **.row** class does not update these negative margins to now be **-25px**. However if I add the additional class **.row@xl** it puts the right margins.

Is this intentional? I feel like it should automatically change the negative margin on breakpoints so I don't have to add more classes that feel unnecessary.

**Comment by olivierbossel** [comment]
Hi,

Thanks for you feedback and sorry for the late answer. I've had some hard times working on another project that will come asap.
I will check your issue and make a new minor release if needed. I let you know!

Cheers!

**Comment by olivierbossel** [comment]
You can download the latest 2.0.45 release that will normally fix your issue.
Let me know!
Cheers!

**Comment by sascha-egerer** [comment]
@olivierbossel The problem does still exist. At least in 2.0.48 i've the same problem. Can you confirm that?

**Comment by sascha-egerer** [comment]
@olivierbossel Sorry for disturbing you but this is just a quick reminder...

**Comment by vaidik** [comment]
Yes this is still an issue in 2.0.48. It'd be great if we can fix this.
